var BoardsConstants = {
  ALL_BOARDS_RECEIVED: "ALL_BOARDS_RECEIVED",
  SINGLE_BOARD_RECEIVED: "SINGLE_BOARD_RECEIVED",
  SINGLE_BOARD_REMOVED: "SINGLE_BOARD_REMOVED"
};

module.exports = BoardsConstants;
